### ISSUE TITLE
Darstellungsfehler

### ISSUE THREAD

**Issue by nofreeWyfy** [maxluetkemeyer/blood-donation-app#3]
Mir sind beim Anschauen der App ein paar Darstellungsfehler auf meinem Gerät (Galaxy A5) aufgefallen. Überwiegend handelt es sich um "Bottom overflows" (s. Bilder).
Bei der Karte verhält es sich aktuell bei meinem Gerät so, dass ich diese lediglich bedienen kann und wenn ich versuche nach unten zur Adresse etc zu gelangen, ich immer in der Karte scrolle, weil sie zu groß ist.

![Screenshot_1](https://user-images.githubusercontent.com/62378448/137315165-229d66bd-1ca5-49d7-b94b-875cf2b3d40c.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/62378448/137315153-04044ae4-978f-4dc1-96f6-321190e9e561.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/62378448/137315155-25a09cd6-40cb-4861-960c-644d668d1306.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/62378448/137315160-74954e54-90e5-4c1f-b1b4-527aad81b666.jpg)

**Comment by maxluetkemeyer** [comment]
Fehler wird angegangen, wenn das finale Design angegangen wird mit dem neuem Material Design 3
